server:
  port: 9090
#  port: 5018

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    username: xm-cn
    password: 123456
    url: jdbc:mysql://localhost:3306/xm-cn?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

# 配置mybatis实体和xml映射
mybatis:
  # 映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    #驼峰命名法，将数据库中department_id转化成java中的departmentId

# 文件上传的前缀url
#fileBaseUrl: http://106.55.55.56:5018
fileBaseUrl: http://localhost:9090